version: '3.8'

services:
  inspec:
    build: .
    image: poc-aws-circleci-inspec-terraform:0.0.1
    container_name: poc_aws_circleci_inspec_terraform
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ASSUME_ROLE_ARN: ${ASSUME_ROLE_ARN}
    volumes: [.:/usr/local/src]
