version: '3.8'

services:
  aws-terraform-inspec:
    build: .
    image: zaslow/poc-aws-circleci-inspec-terraform:0.0.1
    container_name: aws_terraform_inspec
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes: [.:/usr/local/src]
