version: 2.1

jobs:
  run_inspec:
    docker: [image: zaslowd/poc-aws-circleci-inspec-terraform:0.0.1]
    steps:
      - checkout
      - run: ./docker-entrypoint.sh

workflows:
  build-test-compliance:
    jobs:
      - run_inspec
