version: 2.1

jobs:
  run_inspec:
    docker: [image: zaslowd/aws-inspec:0.0.2]
    steps:
      - checkout
      - run: ./docker-entrypoint.sh

workflows:
  compliance-tests:
    jobs:
      - run_inspec
